name-template: 🏷 v$RESOLVED_VERSION
tag-template: v$RESOLVED_VERSION
categories:
  - title: 🚀 新功能
    labels:
      - feature
      - feat
      - enhancement
  - title: 🐛 修复
    labels:
      - fix
      - bugfix
      - bug
  - title: 🧰 维护
    labels:
      - chore
      - refactor
      - perf
  - title: 📝 文档
    labels:
      - docs
      - documentation
  - title: 🎨 样式
    labels:
      - style
      - formatting
  - title: 📦 打包
    labels:
      - build
      - package
  - title: 🚧 其他
    labels:
      - other
      - misc
      - test
      - ci
      - security
      - typescript
      - types
      - lint
      - release
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
  default: patch
template: |
  ## 更新内容

  $CHANGES
