name-template: 🏷 v$RESOLVED_VERSION
tag-template: v$RESOLVED_VERSION
categories:
  - title: 🚀 新增
    labels:
      - enhancement
  - title: 🐛 问题
    labels:
      - bugfix
  - title: 🧰 维护
    labels:
      - maintenance
      - security
  - title: 📝 文档
    labels:
      - documentation
  - title: 📦 依赖/构建
    labels:
      - configuration
  - title: 🚧 其他
    labels:
      - test
      - other
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
  default: patch
template: |
  ## 更新内容

  $CHANGES
