name-template: '🏷 v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 新功能'
    labels:
      - 'feat'
  - title: '🐛 问题修复'
    labels:
      - 'fix'
      - 'bug'
  - title: '🧰 维护'
    labels:
      - 'chore'
      - 'refactor'
      - 'perf'
  - title: '📝 文档'
    labels:
      - 'docs'
  - title: '🎨 样式'
    labels:
      - 'style'
  - title: '🚧 其他'
    labels:
      - 'ci'
      - 'build'
      - 'test'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## 变化

  $CHANGES
