name: Check Build

on: [push, pull_request]

jobs:
  check:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      matrix:
        node_version: [18.x]
        os: [ubuntu-latest]
        build_cmd: ['build:h5', 'build:mp-weixin']
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: pnpm

      - name: Install
        run: pnpm i

      - name: Reset
        run: pnpm run reset-manifest

      - name: Lint
        run: pnpm run lint

      - name: Typecheck
        run: pnpm run type-check

      - name: Build
        run: pnpm run ${{ matrix.build_cmd }}
